# Generated by Django 4.1.7 on 2023-03-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='1', max_length=20),
        ),
    ]
