# Generated by Django 4.1.7 on 2023-03-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_users_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='absent',
            field=models.CharField(default=0, max_length=200, verbose_name='Absent'),
        ),
        migrations.AddField(
            model_name='users',
            name='present',
            field=models.CharField(default=0, max_length=200, verbose_name='Present'),
        ),
    ]
