# Generated by Django 4.1.7 on 2023-03-31 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_users_account_open_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='account_open',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Account Open'),
        ),
    ]
