# Generated by Django 4.1.7 on 2023-04-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_users_account_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='account_open',
            field=models.CharField(default=0, max_length=200, verbose_name='Account Open'),
        ),
    ]
