# Generated by Django 4.1.7 on 2023-04-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_users_account_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='account_open_time',
            field=models.CharField(default=0, max_length=200, verbose_name='Time'),
        ),
    ]
