# Generated by Django 4.1.7 on 2023-04-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_users_account_open_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_suspend',
        ),
        migrations.AddField(
            model_name='users',
            name='is_signin',
            field=models.BooleanField(default=False, verbose_name='Today Status'),
        ),
    ]
